### Trace inference and preparing for visualization in the frontend

In [2]:
import numpy as np
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt
import psycopg

In [3]:
conn_info = "postgres://postgres:admin@localhost:5435/postgres?sslmode=disable"

try:
    # Connect to an existing database
    conn = psycopg.connect(conn_info)

except Exception as e:
    print(f"Error: {e}")

In [7]:
def get_distinct_trace_hops_by_dst_ip(conn, serial_id, dst_ip):
    sql = """
    SELECT
          h.ttl,
          host(h.ip)        AS ip,
          h.asn,
          COUNT(*)          AS observations,
          COUNT(*) FILTER (WHERE h.icmp_type IS NOT NULL) AS replies,
          MAX(h.timestamp)  AS last_seen
      FROM trace_hops h
      JOIN trace_measurements m ON m.id = h.measurement_id
      WHERE m.serial_id = %s
        AND host(m.dst::inet) = %s
        AND h.timestamp > now() - interval '20 minutes'
        AND h.ttl <= m.hop_count
      GROUP BY h.ttl, h.ip, h.asn
      ORDER BY h.ttl, observations DESC;
    """

    with conn.cursor() as cur:
        cur.execute(sql, (serial_id, dst_ip))
        rows = cur.fetchall()
        columns = [desc[0] for desc in cur.description]
        df = pd.DataFrame(rows, columns=columns)
        return df

In [12]:
def distinct_trace_links_by_dst_ip(conn, serial_id, dst_ip):
    sql = """
    WITH ordered_hops AS (
          SELECT
              h.measurement_id,
              h.ttl,
              host(h.ip) AS ip,
              h.asn
          FROM trace_hops h
          JOIN trace_measurements m ON m.id = h.measurement_id
          WHERE m.serial_id = %s
            AND host(m.dst::inet) = %s
            AND h.timestamp > now() - interval '20 minutes'
            AND h.ttl <= m.hop_count
      )
      SELECT
          a.ttl       AS from_ttl,
          a.ip        AS from_ip,
          a.asn       AS from_asn,
          b.ip        AS to_ip,
          b.asn       AS to_asn,
          COUNT(*)    AS observations
      FROM ordered_hops a
      JOIN ordered_hops b
        ON b.measurement_id = a.measurement_id
      AND b.ttl = a.ttl + 1
      GROUP BY a.ttl, a.ip, a.asn, b.ip, b.asn
      ORDER BY a.ttl, observations DESC;
    """

    with conn.cursor() as cur:
        cur.execute(sql, (serial_id, dst_ip))
        rows = cur.fetchall()
        columns = [desc[0] for desc in cur.description]
        df = pd.DataFrame(rows, columns=columns)
        return df

In [13]:
SERIAL_ID = "ap1"
DST_IP = "1.1.1.1"

trace_hops = get_distinct_trace_hops_by_dst_ip(conn, SERIAL_ID, DST_IP)
trace_links = distinct_trace_links_by_dst_ip(conn, SERIAL_ID, DST_IP)

In [16]:
trace_hops.head(10)

,ttl,ip,asn,observations,replies,last_seen
0,1,10.0.1.1,0.0,32,32,2026-05-04 04:26:18.484535+00:00
1,2,10.0.0.2,0.0,13,13,2026-05-04 04:26:18.484535+00:00
2,2,10.0.0.6,0.0,13,13,2026-05-04 04:24:37.961573+00:00
3,2,NaN,NaN,12,0,2026-05-04 04:26:18.484535+00:00
4,2,10.0.0.10,0.0,2,2,2026-05-04 04:20:28.314905+00:00
5,3,10.0.0.10,0.0,14,14,2026-05-04 04:26:18.484535+00:00
6,3,192.168.121.1,0.0,13,13,2026-05-04 04:25:33.082732+00:00
7,3,NaN,NaN,12,0,2026-05-04 04:24:37.961573+00:00
8,3,10.0.0.6,0.0,1,1,2026-05-04 04:18:04.125018+00:00
9,4,NaN,NaN,31,0,2026-05-04 04:25:33.082732+00:00

In [17]:
trace_links.head(10)

   from_ttl   from_ip  from_asn          to_ip  to_asn  observations
0         1  10.0.1.1       0.0       10.0.0.2     0.0            13
1         1  10.0.1.1       0.0       10.0.0.6     0.0            13
2         1  10.0.1.1       0.0            NaN     NaN            12
3         1  10.0.1.1       0.0      10.0.0.10     0.0             2
4         2  10.0.0.2       0.0      10.0.0.10     0.0            11
5         2  10.0.0.6       0.0            NaN     NaN             9
6         2  10.0.0.6       0.0  192.168.121.1     0.0             8
7         2       NaN       NaN  192.168.121.1     0.0             7
8         2       NaN       NaN      10.0.0.10     0.0             5
9         2       NaN       NaN            NaN     NaN             3